import { Pencil, Plus, ShieldCheck } from "lucide-react";
import { ActivityTimeline } from "@/components/ActivityTimeline";
import { InitialsAvatar, Modal, StatusChip, type StatusTone } from "@/components/DesignSystem";
import { MemberCardPanel } from "@/components/membership/MemberCardPanel";
import { MembershipPanel } from "@/components/membership/MembershipPanel";
import { useAuth } from "@/contexts/AuthContext";
import { ICON_SIZE } from "@/lib/icon-sizes";
import { MEMBERSHIP_VIEW_ROLES, hasRole } from "@shared/roles";
import { MEMBERSHIP_STATUS_LABELS } from "@shared/labels";
import type { MembershipStatus } from "@shared/schema";
import type { Member } from "./types";

/**
 * MemberDetailModal — detail view for a single member (Phase 6B).
 *
 * Extracted from Members.tsx — no changes to behavior, styling, or logic.
 * Pure presentation: receives member data and callbacks, makes no API calls.
 *
 * URL state (selectedMemberId) stays in the parent. This component receives
 * the resolved `member` object and renders it.
 *
 * Props:
 * - member: the member to display (null = closed)
 * - qrCodeDataUrl: QR code image data URL (generated by parent)
 * - onClose: close the modal (clears URL param in parent)
 * - onEdit: open edit form for this member
 * - onCreateFollowUp: create a follow-up for this member
 * - creatingFollowUp: mutation state for the follow-up button
 * - canManage: permission flag for the edit button
 */

const MEMBERSHIP_STATUS_TONES: Record<MembershipStatus, StatusTone> = {
  active: "success",
  visitor: "info",
  candidate: "warning",
  transferred: "neutral",
  inactive: "error",
};

function formatDate(iso: string | null) {
  if (!iso) return "-";
  return new Date(iso).toLocaleDateString("th-TH", {
    day: "numeric",
    month: "short",
    year: "numeric",
  });
}

interface MemberDetailModalProps {
  member: Member | null;
  qrCodeDataUrl: string;
  onClose: () => void;
  onEdit: (member: Member) => void;
  onCreateFollowUp: () => void;
  creatingFollowUp: boolean;
  canManage: boolean;
}

export function MemberDetailModal({
  member: selectedMember,
  qrCodeDataUrl,
  onClose: closeMember,
  onEdit: openEdit,
  onCreateFollowUp: handleCreateFollowUp,
  creatingFollowUp,
  canManage,
}: MemberDetailModalProps) {
  const { user } = useAuth();
  const canSeeMembership = hasRole(user?.role, MEMBERSHIP_VIEW_ROLES);
  return (
    <Modal
      open={selectedMember !== null}
      onClose={closeMember}
      title="ข้อมูลสมาชิก"
      description={selectedMember?.name}
      size="wide"
      footer={
        <>
          <button
            type="button"
            onClick={closeMember}
            className="inline-flex min-h-11 items-center justify-center rounded-[var(--radius-pill)] border border-[var(--color-hairline)] px-5 text-sm font-semibold text-[var(--color-ink)] transition-colors hover:bg-[var(--color-canvas-soft)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--color-primary-focus)]"
          >
            ปิด
          </button>
          <button
            type="button"
            onClick={handleCreateFollowUp}
            disabled={creatingFollowUp}
            className="inline-flex min-h-11 items-center justify-center gap-2 rounded-[var(--radius-pill)] border border-[var(--color-primary)] px-5 text-sm font-semibold text-[var(--color-primary)] transition-colors hover:bg-[var(--color-accent-soft)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--color-primary-focus)] disabled:opacity-50"
          >
            <Plus size={ICON_SIZE.sm} aria-hidden="true" />
            {creatingFollowUp ? "กำลังสร้าง…" : "สร้างรายการติดตาม"}
          </button>
          {canManage && (
            <button
              type="button"
              onClick={() => {
                const target = selectedMember;
                closeMember();
                if (target) openEdit(target);
              }}
              className="inline-flex min-h-11 items-center justify-center gap-2 rounded-[var(--radius-pill)] bg-[var(--color-primary)] px-5 text-sm font-semibold text-[var(--color-on-primary)] transition-colors hover:bg-[var(--color-primary-focus)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--color-primary-focus)]"
            >
              <Pencil size={ICON_SIZE.sm} aria-hidden="true" />
              แก้ไขข้อมูล
            </button>
          )}
        </>
      }
    >
      {selectedMember && (
        <div className="space-y-5">
          <div className="flex flex-wrap items-center gap-4 rounded-[var(--radius-lg)] bg-[var(--color-canvas-soft)] p-4">
            <InitialsAvatar name={selectedMember.name} size={56} />
            <div className="min-w-0 flex-1">
              <p className="type-body-strong text-[var(--color-ink)]">
                {selectedMember.name}
                {selectedMember.nickname ? ` (${selectedMember.nickname})` : ""}
              </p>
              <div className="mt-2 flex flex-wrap items-center gap-1.5">
                <StatusChip tone="neutral">{selectedMember.role}</StatusChip>
                <StatusChip tone={MEMBERSHIP_STATUS_TONES[selectedMember.membershipStatus]}>
                  {MEMBERSHIP_STATUS_LABELS[selectedMember.membershipStatus] ??
                    selectedMember.membershipStatus}
                </StatusChip>
                <StatusChip
                  tone={selectedMember.status === "ติดตามแล้ว" ? "success" : "warning"}
                >
                  {selectedMember.status}
                </StatusChip>
                {selectedMember.consentGiven && (
                  <StatusChip tone="success">
                    <ShieldCheck size={12} aria-hidden="true" className="mr-1" />
                    ยินยอม PDPA แล้ว
                  </StatusChip>
                )}
              </div>
            </div>
            {qrCodeDataUrl && (
              <div className="shrink-0 rounded-[var(--radius-md)] border border-[var(--color-hairline)] bg-[var(--color-canvas)] p-2 text-center">
                <img
                  src={qrCodeDataUrl}
                  alt={`รหัส QR สำหรับเช็คชื่อของ ${selectedMember.name}`}
                  width={80}
                  height={80}
                  className="block size-20"
                />
                <p className="type-fine mt-1 text-[var(--color-body-muted)]">รหัสเช็คชื่อ</p>
              </div>
            )}
          </div>

          <section aria-labelledby="member-card-title">
            <h3 id="member-card-title" className="type-caption-strong mb-2 text-[var(--color-ink)]">
              บัตรสมาชิก
            </h3>
            <MemberCardPanel memberId={selectedMember.id} />
          </section>

          {canSeeMembership && (
            <section aria-labelledby="membership-title">
              <h3 id="membership-title" className="type-caption-strong mb-2 text-[var(--color-ink)]">
                สถานะสมาชิกรายปี
              </h3>
              <MembershipPanel memberId={selectedMember.id} />
            </section>
          )}

          <div className="grid gap-4 sm:grid-cols-2">
            <section className="rounded-[var(--radius-md)] border border-[var(--color-hairline)] p-4">
              <h3 className="type-caption-strong mb-2 text-[var(--color-ink)]">ช่องทางติดต่อ</h3>
              <dl className="type-caption space-y-1.5 text-[var(--color-text-secondary)]">
                <div className="flex gap-2">
                  <dt className="shrink-0">เบอร์โทร:</dt>
                  <dd className="font-semibold text-[var(--color-ink)]">
                    {selectedMember.phone || "ไม่มีข้อมูล"}
                  </dd>
                </div>
                <div className="flex gap-2">
                  <dt className="shrink-0">อีเมล:</dt>
                  <dd className="min-w-0 break-words font-semibold text-[var(--color-ink)]">
                    {selectedMember.email || "ไม่มีข้อมูล"}
                  </dd>
                </div>
                <div className="flex gap-2">
                  <dt className="shrink-0">LINE:</dt>
                  <dd className="font-semibold text-[var(--color-ink)]">
                    {selectedMember.lineId || "ไม่มีข้อมูล"}
                  </dd>
                </div>
                <div className="flex gap-2">
                  <dt className="shrink-0">ที่อยู่:</dt>
                  <dd className="font-semibold text-[var(--color-ink)]">
                    {selectedMember.address || "ไม่มีข้อมูล"}
                  </dd>
                </div>
              </dl>
            </section>

            <section className="rounded-[var(--radius-md)] border border-[var(--color-hairline)] p-4">
              <h3 className="type-caption-strong mb-2 text-[var(--color-ink)]">
                คริสตจักรและผู้ติดต่อฉุกเฉิน
              </h3>
              <dl className="type-caption space-y-1.5 text-[var(--color-text-secondary)]">
                <div className="flex gap-2">
                  <dt className="shrink-0">พื้นที่:</dt>
                  <dd className="font-semibold text-[var(--color-ink)]">
                    {selectedMember.area || "-"}
                  </dd>
                </div>
                <div className="flex gap-2">
                  <dt className="shrink-0">พันธกิจ:</dt>
                  <dd className="font-semibold text-[var(--color-ink)]">
                    {selectedMember.careGroup
                      ? `${selectedMember.careGroup.name}${selectedMember.careGroup.bodyName ? ` · ${selectedMember.careGroup.bodyName}` : ""}`
                      : selectedMember.group || "ยังไม่มีกลุ่ม"}
                  </dd>
                </div>
                <div className="flex gap-2">
                  <dt className="shrink-0">เข้าร่วมเมื่อ:</dt>
                  <dd className="font-semibold tabular-nums text-[var(--color-ink)]">
                    {formatDate(selectedMember.joinedAt)}
                  </dd>
                </div>
                <div className="flex gap-2">
                  <dt className="shrink-0">ผู้ติดต่อฉุกเฉิน:</dt>
                  <dd className="font-semibold text-[var(--color-ink)]">
                    {selectedMember.emergencyContactName
                      ? `${selectedMember.emergencyContactName} (${selectedMember.emergencyContactPhone || "-"})`
                      : "ไม่มีข้อมูล"}
                  </dd>
                </div>
              </dl>
            </section>
          </div>

          {selectedMember.notes && (
            <section className="rounded-[var(--radius-md)] bg-[var(--color-warning-soft)] p-4">
              <h3 className="type-caption-strong mb-1 text-[var(--color-warning)]">
                บันทึกฝ่ายอภิบาล (เห็นเฉพาะเจ้าหน้าที่)
              </h3>
              <p className="type-caption whitespace-pre-line text-[var(--color-ink)]">
                {selectedMember.notes}
              </p>
            </section>
          )}

          <section>
            <h3 className="type-caption-strong mb-2 text-[var(--color-ink)]">
              กิจกรรมพันธกิจล่าสุด
            </h3>
            <ActivityTimeline subjectType="member" subjectId={selectedMember.id} />
          </section>
        </div>
      )}
    </Modal>
  );
}
